create table public.meetings (
    id bigint generated by default as identity primary key,
    topic text not null unique
);

alter table public.meetings enable row level security;

create table public.meeting_users (
  user_id uuid references auth.users (id),
  meeting_topic text references public.meetings (topic),
  created_at timestamptz default current_timestamp,
  is_owner boolean default false
);

alter table public.meeting_users enable row level security;
