create table public.matches (
    id bigint generated by default as identity primary key,
    topic text not null unique
);

alter table public.matches enable row level security;

create table public.match_users (
  user_id uuid references auth.users (id),
  match_topic text references public.matches (topic),
  created_at timestamptz default current_timestamp,
  is_owner boolean default false
);

alter table public.match_users enable row level security;
