create table public.fights (
    id bigint generated by default as identity primary key,
    topic text not null unique
);

alter table public.fights enable row level security;

create table public.fight_users (
  user_id uuid references auth.users (id),
  fight_topic text references public.fights (topic),
  created_at timestamptz default current_timestamp,
  is_owner boolean default false
);

alter table public.fight_users enable row level security;
